spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autobi?characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: ezreal
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 2
    port: 6379
    host: localhost
    password: ezreal
    timeout: 5000

redisson:
  host: localhost
  port: 6379
  password: ezreal
  database: 2
yuapi:
  client:
    access-key: ftpc9kx4akk0df4vhwmspcebk9qthhks
    secret-key: fh5o7fi958v3rb5t586dgpvtfz684ngy
    modelId: 1671122813869625345